<?php
/*
Plugin Name: AJAX Comment Page
Plugin URI: http://mr.hokya.com/ajax-comment-page/
Description: Divides your comments into pages which will be shown animatedly with AJAX and JQuery to help visitor read your comments and give better look on your pages.
Version: 3.25
Author: Julian Widya Perdana
Author URI: http://mr.hokya.com/
*/

if (!get_option("comments_max")) update_option("comments_max",5);

function ajax_comment_page_start() {
	echo '<div id="comment_pager">';
}

function ajax_comment_page_end() {
	$home = get_option("home");
	$max = get_option("comments_max");
	echo "<small>Paged comment generated by <a href='http://mr.hokya.com/ajax-comment-page/' target='_blank'>AJAX Comment Page</a></small>\n";
	echo "<noscript>Please enable javascript to use AJAX Comment Page</noscript>\n";
	echo "<script src='$home/wp-content/plugins/ajax-comment-page/jquery.js'></script>\n";
	echo "<!-- AJAX Comment Page: created by http://mr.hokya.com/ -->\n";
	echo "<script src='$home/wp-content/plugins/ajax-comment-page/js.php?max=$max'></script>\n";
	echo "</div>";
}

function ajax_comment_page_notice () {
	echo "<p>Thanks for using <strong><a href='http://mr.hokya.com/ajax-comment-page/' target='_blank'>AJAX Comment Page</a></strong> to pagerize your comments with jquery animation.</p>";
}

function ajax_comment_page_options() {
	add_options_page('AJAX Comment Page', 'AJAX Comment Page', 'manage_options','ajax-comment-page/options.php');
}

add_action('comments_template','ajax_comment_page_start');
add_action('comment_form','ajax_comment_page_end');
add_action('rightnow_end','ajax_comment_page_notice');
add_action('admin_menu','ajax_comment_page_options');

?>